service: uwo-eats-server

frameworkVersion: '3'

provider:
  name: aws
  runtime: java11
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ca-central-1"}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:BatchGetItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:UpdateItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

package:
  artifact: build/libs/uwo-eats-server-${self:provider.stage}-all.jar

functions:
  store-get:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /store
          method: get
