service: uwo-eats-server

frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ca-central-1"}
  runtime: java11
  architecture: arm64
  environment:
    JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  timeout: 20 # By default, the timeout is 6 seconds, which is too short for cold start
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:BatchGetItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:UpdateItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

package:
  artifact: build/libs/${self:service}-${self:provider.stage}-all.jar

functions:
  store-get:
    handler: uwoEats.api.StoreGetHandler
    events:
      - httpApi:
          path: /store/{id}
          method: get

resources:
  Resources:
    StoreTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-store
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
